/*
Copyright 2016 Dirk Strack

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
--------------------------------------------------------------------------------
declare 
	v_count NUMBER;
	v_stat VARCHAR2(32767);
begin
	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'APP_PREFERENCES';
	if v_count = 0 then 
		v_stat := q'[
		CREATE TABLE APP_PREFERENCES (
			ID                      NUMBER DEFAULT 1 NOT NULL CONSTRAINT APP_PREFERENCES_ID_PK PRIMARY KEY,
			CREATED_BY              VARCHAR2 (32) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')) NOT NULL ,
			CREATED_AT              TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL ,
			LAST_MODIFIED_BY        VARCHAR2 (32) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')) NOT NULL ,
			LAST_MODIFIED_AT        TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL ,
			INFOMAIL_FROM           VARCHAR2(255),
			INFOMAIL_FOOTER			VARCHAR2(1024),
			LIZENZ_NAME				VARCHAR2(255),
			LIZENZ_EMAIL			VARCHAR2(255),
			SMTP_HOST_ADDRESS			VARCHAR2(255),
			SMTP_HOST_PORT				NUMBER(6) DEFAULT 465,
			SMTP_USERNAME				VARCHAR2(255),
			SMTP_PASSWORD				VARCHAR2(64),
			SMTP_SSL					VARCHAR2(1) DEFAULT '1' NOT NULL CHECK (SMTP_SSL IN ('0','1','2')),
			SMTP_SSL_CONNECT_PLAIN 		VARCHAR2(1) DEFAULT '0' NOT NULL CHECK (SMTP_SSL_CONNECT_PLAIN IN ('0','1')),
			WALLET_PATH					VARCHAR2(255),
			WALLET_PASSWORD				VARCHAR2(64)
		)
		]';
		EXECUTE IMMEDIATE v_Stat;
		v_stat := q'[
		ALTER TABLE APP_PREFERENCES ADD CONSTRAINT APP_PREFERENCES_CHECK_ID CHECK(ID = 1)
		]';
		EXECUTE IMMEDIATE v_Stat;
		v_stat := q'[
		ALTER TABLE APP_PREFERENCES ADD CONSTRAINT APP_PREFERENCES_UK UNIQUE(INFOMAIL_FROM)
		]';
		EXECUTE IMMEDIATE v_Stat;
		v_stat := q'[
		CREATE OR REPLACE TRIGGER APP_PREFERENCES_BIU
			BEFORE INSERT OR UPDATE
			ON APP_PREFERENCES
			FOR EACH ROW
		BEGIN
			if :new.ID is null then
				:new.ID := 1;
			end if;
			if inserting then
				:new.CREATED_AT := LOCALTIMESTAMP;
				:new.CREATED_BY := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
			end if;
			:new.LAST_MODIFIED_AT := LOCALTIMESTAMP;
			:new.LAST_MODIFIED_BY := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
		END APP_PREFERENCES_BIU;
		]';
		EXECUTE IMMEDIATE v_Stat;
	end if;
end;
/
show errors

/*
-- uninstall
DROP TABLE APP_PREFERENCES;
DROP TABLE APP_USERS;
DROP TABLE APP_PROTOCOL;
DROP TABLE APP_USER_LEVELS;
DROP TABLE USER_WORKSPACE_SESSIONS;
DROP TABLE USER_NAMESPACES CASCADE CONSTRAINTS;
DROP SEQUENCE USER_NAMESPACES_SEQ;
*/

