declare 
	v_count NUMBER;
	v_stat VARCHAR2(32767);
begin
	SELECT COUNT(*) INTO v_count
	FROM USER_TABLES WHERE TABLE_NAME = 'CHANGE_LOG_CONFIG';
	if v_count = 0 then 
		v_stat := q'[
		CREATE TABLE CHANGE_LOG_CONFIG
		(
			ID                           NUMBER DEFAULT 1 NOT NULL CONSTRAINT CHANGE_LOG_CONFIG_PK PRIMARY KEY,
			INCLUDED_CHANGELOG_PATTERN   VARCHAR2(4000),
			EXCLUDED_CHANGELOG_PATTERN   VARCHAR2(4000),
			CHANGELOG_FKEY_TABLES        VARCHAR2(4000),
			CHANGELOG_FKEY_COLUMNS       VARCHAR2(4000),
			REFERENCE_DESCRIPTION_COLS   VARCHAR2(4000),
			EXCLUDED_CHANGELOG_BLOB_COLS VARCHAR2(4000),
			EXCLUDED_CHANGELOG_COLS      VARCHAR2(4000),
			COPY_BEFORE_IMAGE            VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (COPY_BEFORE_IMAGE IN ('YES','NO')),
			BASE_TABLE_EXT               VARCHAR2(64),
			CHANGELOG_VIEW_EXT           VARCHAR2(64),
			HISTORY_VIEW_EXT             VARCHAR2(64),
			-----------------------------------------------------------------------
			TABLE_APP_USERS              VARCHAR2(64),
			USE_AUDIT_INFO_COLUMNS       VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (USE_AUDIT_INFO_COLUMNS IN ('YES','NO')),
			DROP_AUDIT_INFO_COLUMNS      VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (DROP_AUDIT_INFO_COLUMNS IN ('YES','NO')),
			USE_AUDIT_INFO_TRIGGER       VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (USE_AUDIT_INFO_TRIGGER IN ('YES','NO')),
			USE_CHANGE_LOG 			     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (USE_CHANGE_LOG IN ('YES','NO')),
			ADD_COLUMN_WORKSPACE_ID      VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_WORKSPACE_ID IN ('YES','NO')),
			ADD_COLUMN_DELETE_MARK       VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_DELETE_MARK IN ('YES','NO')),
			ADD_COLUMN_MODIFY_DATE		 VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_MODIFY_DATE IN ('YES','NO')),
			ADD_COLUMN_MODIFY_USER		 VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_MODIFY_USER IN ('YES','NO')),
			ADD_COLUMN_CREATION_DATE	 VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_CREATION_DATE IN ('YES','NO')),
			ADD_COLUMN_CREATION_USER	 VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_COLUMN_CREATION_USER IN ('YES','NO')),
			ENFORCE_NOT_NULL             VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ENFORCE_NOT_NULL IN ('YES','NO')),
			ADD_INSERT_TRIGGER		     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_INSERT_TRIGGER IN ('YES','NO')),
			ADD_DELETE_TRIGGER		     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_DELETE_TRIGGER IN ('YES','NO')),
			ADD_UPDATE_TRIGGER1		     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_UPDATE_TRIGGER1 IN ('YES','NO')),
			ADD_UPDATE_TRIGGER2		     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_UPDATE_TRIGGER2 IN ('YES','NO')),
			ADD_APPLICATION_SCHEMA		 VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_APPLICATION_SCHEMA IN ('YES','NO')),
			ADD_CHANGELOG_VIEWS		     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (ADD_CHANGELOG_VIEWS IN ('YES','NO')),
			USE_ON_NULL_DEFAULTS         VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (USE_ON_NULL_DEFAULTS IN ('YES','NO')),
			USE_SEQUENCES                VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (USE_SEQUENCES IN ('YES','NO')),
			INCLUDE_EXTERNAL_OBJECTS     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (INCLUDE_EXTERNAL_OBJECTS IN ('YES','NO')),
			INCLUDED_WORKSPACEID_PATTERN VARCHAR2(4000),
			EXCLUDED_WORKSPACEID_PATTERN VARCHAR2(4000),
			INCLUDED_DELETE_MARK_PATTERN VARCHAR2(4000),
			EXCLUDED_DELETE_MARK_PATTERN VARCHAR2(4000),
			INCLUDED_TIMESTAMP_PATTERN   VARCHAR2(4000),
			EXCLUDED_TIMESTAMP_PATTERN   VARCHAR2(4000),
			INCLUDED_HIST_VIEWS_PATTERN	 VARCHAR2(4000),
			EXCLUDED_HIST_VIEWS_PATTERN	 VARCHAR2(4000),
			COLUMN_WORKSPACE             VARCHAR2(64),
			COLUMN_CREATE_USER           VARCHAR2(512),
			COLUMN_CREATE_DATE           VARCHAR2(512),
			COLUMN_MODIFY_USER           VARCHAR2(512),
			COLUMN_MODIFY_DATE           VARCHAR2(512),
			COLUMN_DELETED_MARK          VARCHAR2(512),
			COLUMN_INDEX_FORMAT          VARCHAR2(512),
			-----------------------------------------------------------------------
			DATATYPE_MODIFY_USER         VARCHAR2(64),
			COLUMNTYPE_MODIFY_USER       VARCHAR2(64),
			IS_FOREIGN_KEY_MODIFY_USER   VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (IS_FOREIGN_KEY_MODIFY_USER IN ('YES','NO')),
			FUNCTION_MODIFY_USER         VARCHAR2(512),
			FUNCTION_MODIFY_DATE         VARCHAR2(512),
			DATATYPE_MODIFY_DATE         VARCHAR2(64),
			DATATYPE_MODIFY_DATE_ALT     VARCHAR2(64),
			DATATYPE_DELETED_MARK        VARCHAR2(64),
			COLUMNTYPE_DELETED_MARK      VARCHAR2(64),
			DEFAULT_DELETED_MARK         VARCHAR2(64),
			SEQUENCE_EXT                 VARCHAR2(64),
			SEQUENCE_COLUMN_EXT          VARCHAR2(64),
			SEQUENCE_CONSTRAINT_EXT      VARCHAR2(64),
			SEQUENCE_OPTIONS             VARCHAR2(64),
			INTERRIM_TABLE_EXT           VARCHAR2(64),
			CHANGE_LOG_TRIGGER_PREFIX	 VARCHAR2(64),
			CHANGE_LOG_TRIGGER_EXT		 VARCHAR2(64),
			BI_TRIGGER_PREFIX            VARCHAR2(64),
			BI_TRIGGER_EXT               VARCHAR2(64),
			BU_TRIGGER_PREFIX            VARCHAR2(64),
			BU_TRIGGER_EXT               VARCHAR2(64),
			INS_TRIGGER_PREFIX           VARCHAR2(64),
			INS_TRIGGER_EXT              VARCHAR2(64),
			DEL_TRIGGER_PREFIX           VARCHAR2(64),
			DEL_TRIGGER_EXT              VARCHAR2(64),
			UPD_TRIGGER_PREFIX           VARCHAR2(64),
			UPD_TRIGGER_EXT              VARCHAR2(64),
			LAST_MODIFIED_AT 			 TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT LOCALTIMESTAMP NOT NULL ENABLE,
			LAST_MODIFIED_BY 			 VARCHAR2(32 CHAR) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER')) NOT NULL ENABLE
		)
		]';
		EXECUTE IMMEDIATE v_Stat;
		v_stat := q'[
		CREATE OR REPLACE TRIGGER CHANGE_LOG_CONFIG_BU_TR
		BEFORE UPDATE ON CHANGE_LOG_CONFIG FOR EACH ROW
		BEGIN
			:new.LAST_MODIFIED_BY := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','SESSION_USER'));
			:new.LAST_MODIFIED_AT   := LOCALTIMESTAMP;
		END;
		]';
		EXECUTE IMMEDIATE v_Stat;
	end if;
	SELECT COUNT(*) INTO v_count
	FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CHANGE_LOG_CONFIG' AND COLUMN_NAME = 'EXCLUDED_HIST_VIEWS_PATTERN';
	if v_count = 0 then 
		v_stat := q'[
		ALTER TABLE CHANGE_LOG_CONFIG ADD 
		(
			INCLUDED_HIST_VIEWS_PATTERN	VARCHAR2(4000),
			EXCLUDED_HIST_VIEWS_PATTERN	VARCHAR2(4000)
		)
		]';
		EXECUTE IMMEDIATE v_Stat;
	end if;
		
end;
/


declare
	v_Count PLS_INTEGER;
begin
	SELECT COUNT(*) INTO v_Count
	from user_tab_cols where table_name = 'CHANGE_LOG_CONFIG' and column_name = 'INCLUDE_EXTERNAL_OBJECTS';
	if v_Count = 0 then
		EXECUTE IMMEDIATE q'[ALTER TABLE CHANGE_LOG_CONFIG ADD (
			INCLUDE_EXTERNAL_OBJECTS     VARCHAR2(3) DEFAULT 'NO' NOT NULL CHECK (INCLUDE_EXTERNAL_OBJECTS IN ('YES','NO'))
		)]';
	end if;	
	SELECT COUNT(*) INTO v_Count
	from user_tab_cols where table_name = 'CHANGE_LOG_CONFIG' and column_name = 'COLUMN_CREATE_USER' and CHAR_LENGTH = 64;
	if v_Count = 1 then
		EXECUTE IMMEDIATE q'[ALTER TABLE CHANGE_LOG_CONFIG MODIFY (
			COLUMN_CREATE_USER           VARCHAR2(512),
			COLUMN_CREATE_DATE           VARCHAR2(512),
			COLUMN_MODIFY_USER           VARCHAR2(512),
			COLUMN_MODIFY_DATE           VARCHAR2(512),
			COLUMN_DELETED_MARK          VARCHAR2(512),
			COLUMN_INDEX_FORMAT          VARCHAR2(512)
		)]';
		UPDATE CHANGE_LOG_CONFIG
		SET COLUMN_CREATE_USER = 'CREATED_BY,ERFASST_VON,ERFASST_KUERZEL',
			COLUMN_CREATE_DATE = 'CREATED_AT,CREATED,ERFASST_DATUM',
			COLUMN_MODIFY_USER = 'LAST_MODIFIED_BY,MODIFIED_BY,UPDATED_BY,AENDERUNG_KUERZEL',
			COLUMN_MODIFY_DATE = 'LAST_MODIFIED_AT,MODIFIED,UPDATED,CONFIG_TIME,AENDERUNG_DATUM';
		COMMIT;
	end if;	
	SELECT COUNT(*) INTO v_Count
	from user_tab_cols where table_name = 'CHANGE_LOG_CONFIG' and column_name = 'FUNCTION_MODIFY_USER' and CHAR_LENGTH = 64;
	if v_Count = 1 then
		EXECUTE IMMEDIATE q'[ALTER TABLE CHANGE_LOG_CONFIG MODIFY (
			FUNCTION_MODIFY_USER         VARCHAR2(512),
			FUNCTION_MODIFY_DATE         VARCHAR2(512)
		)]';
	end if;	
end;
/


